name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use Node.js version 18.x to match Next.js requirements

      - name: Install dependencies
        run: yarn install

      - name: Verify directory structure
        run: |
          if [ ! -d "frontend/src/app" ]; then
            echo "Error: No 'app' directory found under 'frontend/src'!" && exit 1
          fi

      - name: Build the application
        run: |
          # Change to the frontend directory before building
          cd frontend
          yarn run build

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
